### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by BG2ENW** [int2001/DXClusterAPI#24]
Error in operation, loop restarting.

TypeError: undefined is not an object (evaluating 'config.includepotaspots')
  at /usr/src/app/index.js:204:4

![Image](https://github.com/user-attachments/assets/e550658e-2605-4f85-adf9-d1a991039b17)

![Image](https://github.com/user-attachments/assets/dd5e524e-2e5b-4c73-b5ba-f9be46f464a1)

**Comment by BG2ENW** [comment]
version: '3'
services:
  dxcache:
    build:
      dockerfile: ./Dockerfile
    container_name: dxclustercache
    environment:
      MAXCACHE: 100	# Max Spots to cache
      WEBPORT: 8192	# Port the App should listen on for Requests (see ports here)
      WAVELOG_URL: http://ip/index.php/api/lookup	# Wavelog-API-Endpoint for looking up DXCC
      WEBURL: /t	# sub-url. e.g. if "/t" the application can be reached via "http://[ip]/t/stats" etc.
      WAVELOG_KEY: xxxxxxx	# Key from wavelog-api
      DXHOST: dxfun.com	# DNS of DXCluster upstream
      DXPORT: 8000	# Port of DXCluster upstream
      DXCALL: BG2ENW	# Login-Call for Cluster
      DXPASSWORD: xxxxx	# Login-Passwort for Cluster (in most of all cases leave this blank!!
      POTA_INTEGRATION: false	# wether to poll POTA for spots
      POTA_POLLING_INTERVAL: 120	# polling interval for POTA in seconds
    ports:
      - 8192:8192	# Exposed port - see WEBPORT above
    restart: unless-stopped

**Comment by int2001** [comment]
try to remove the comments after each line.
Depending on your docker-compose Setup it doesn't like the inline-comments at `docker-compose.yaml`.

The errors you pasted are pointing to some issue parsing the config correctly.

So play around with the values at `environment`-section:
- removing the comments there
- putting the strings into quotes (e.g.: `POTA_INTEGRATION: "false"` instead of `POTA_INTEGRATION: false`

**Comment by BG2ENW** [comment]
There are still errors after the modification
error: ENOENT while resolving package 'ms' from '/home/bun/.bun/install/cache/debug@4.4.1@@@1/src/common.js'

Bun v1.2.13 (Linux x64 baseline)

**Comment by int2001** [comment]
rechecked it with a fresh `git pull` on my side and configured docker-compose.
works without problems here (and on a lot of other instances) - so its not really a bug.

it seems like some kind of firewall is nagging you. the new Errormessage points to the fact that docker was unable to fetch some specific packets which are needed to run it.

Try the prebuilt instead. Perhaps this works with your setup:
docker-compose.yaml:
```
version: '3'
services:
  dxcache:
    image: ghcr.io/int2001/dxclusterapi:latest
    container_name: dxcache
    environment:
      MAXCACHE: 100
      WEBPORT: 8192	
      WAVELOG_URL: https://[your wavelog-instance]/index.php/api/lookup
      WEBURL: /t
      WAVELOG_KEY: [your wavelog_key]
      DXHOST: dxfun.com
      DXPORT: 8000
      DXCALL: BG2ENW
      DXPASSWORD:
      POTA_INTEGRATION: false
      POTA_POLLING_INTERVAL: 120
    ports:
      - 8192:8192
    restart: unless-stopped
```
